version: 0.2

phases:
  pre_build:
    commands:
      - curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
      - sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
      - sudo apt-get update && sudo apt-get install terraform
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
      - terraform apply -auto-approve
    finally:
      - echo This always runs even if the install command fails