version: 0.2

phases:
  pre_build:
    commands:
      - ./build/pre-build.sh
  build:
    commands:
      - ./build/build.sh
    finally:
      - echo This always runs even if the install command fails