version: 0.2

phases:
  pre_build:
    commands:
      - echo Install terraform
      - curl -fsSL https://apt.releases.hashicorp.com/gpg | apt-key add -
      - apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
      - apt-get update && apt-get install terraform
      - echo Install nvm
      - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
      - source ~/.bashrc
      - nvm install lts
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
      - nvm use lts
      - terraform apply -auto-approve
    finally:
      - echo This always runs even if the install command fails