[[redirects]]
  from = "/api/*"
  to = "http://lifedatabase-822610598.us-west-2.elb.amazonaws.com/:splat"
  status = 200
  force = true # COMMENT: ensure that we always redirect
  signed = "API_SIGNATURE_TOKEN_PLACEHOLDER"

[[redirects]]
  from = "/headers"
  to = "https://httpbin.org/headers"
  status = 200
  signed = "PROXY_REQUEST_KEY"
